version: "3"

services:
    client:
        stdin_open: true
        build: ./client
        ports:
            - 3000:3000
        volumes:
            - ./client:/usr/src/app/client
            - node_modules:/usr/src/app/client/node_modules

    server:
        build: .
        ports:
            - 5000:3000
        volumes:
            - .:/usr/src/app
            - node_modules_b:/usr/src/app/node_modules

volumes:
    node_modules:
    node_modules_b:
